version: "2"

run:
  go: "1.23"
  timeout: 3m

linters:
  default: standard
  enable:
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
